### ISSUE TITLE
Does not load chunks in the end

### ISSUE THREAD

**Issue by TheDemitrius** [LexManos/ChunkNoGoByeBye#5]
Whilst chunks can be unmarked when item is destroyed in the end, chunks are not marked when the item is put down.

**Comment by LexManos** [comment]
They are, if the message doesn't show when you place a block that is because something else {possibly another CNGBB block} is already loading the chunk.
Notice how there are no xp orbs in the chunk i'm in, that is because there is a chunk loader in it and they timed out while the others were unloaded.
![](https://i.imgur.com/TTQfnsM.jpg)
